set(SNAPPY_LIBRARY_NAME snappy)

if(NOT USE_SYSTEM_SNAPPY)
    option(SNAPPY_BUILD_TESTS "Build Snappy's own tests." OFF)
    if(NOT SNAPPY_ROOT_DIR)
        set(SNAPPY_ROOT_DIR ${CMAKE_CURRENT_SOURCE_DIR}/third_party/snappy)
    endif()

    if(EXISTS "${SNAPPY_ROOT_DIR}/CMakeLists.txt")
        add_subdirectory(${SNAPPY_ROOT_DIR}/ third_party/snappy)
        if(TARGET ${SNAPPY_LIBRARY_NAME})
            set(SNAPPY_LIBRARY ${SNAPPY_LIBRARY_NAME})
        endif()
        set(SNAPPY_INCLUDE_DIR "${SNAPPY_ROOT_DIR}/include")
        set(SNAPPY_LIBRARY_DIR ${CMAKE_CURRENT_BINARY_DIR}/third_party/snappy)
    else()
        message(WARNING "SNAPPY_ROOT_DIR is wrong")
    endif()
else()
    find_path(SNAPPY_INCLUDE_DIR NAMES "snappy.h")
    find_library(SNAPPY_LIBRARY NAMES ${SNAPPY_LIBRARY_NAME})
    get_filename_component(ABS_SNAPPY_LIB ${SNAPPY_LIBRARY} ABSOLUTE)
    get_filename_component(SNAPPY_LIBRARY_DIR ${ABS_SNAPPY_LIB} DIRECTORY)
endif()
